### ISSUE TITLE
How to rotate the widget ?

### ISSUE THREAD

**Issue by codinghedgehog-python** [kivy-garden/xcamera#31]
Just as standard Camera widget that comes with Kivy, XCamera loads rotated 90 degrees on my Samsung.

with standard camera widget I can do:
```

Camera:
        id: camera
        canvas.before:
            PushMatrix:
            Rotate:
                angle: -90
                origin: root.width/2, root.height/2
        canvas.after:
            PopMatrix:
```

But when I do the same using XCamera the app crashes.
Any feedback much appreciated.
